mode: "train"  # "train" or "eval"

MAX_SEQ_LEN: 524
MIN_FREQ: 2  # min frequency for vocab
PADDING_IDX: 0
UNK_IDX: 1

# Model params
EMBEDDING_DIM: 64
HIDDEN_DIM: 32
DROPOUT: 0.3
NUM_CLASSES: 10  # will update after loading punctuation list

# Training
BATCH_SIZE: 16
EPOCHS: 20
LEARNING_RATE: 3e-4

SCHEDULER_PATIENCE: 2
EARLY_STOPPING_PATIENCE: 5
LR_REDUCTION_FACTOR: 0.5
SCHEDULER_THRESHOLD: 0.0001

# Files
TRAIN_DIR: "data/train/"
VAL_DIR: "data/val/"
TEST_DIR: "data/eval/"
VOCAB_PATH: "data/vocab.json"
LABEL2ID_PATH: "data/label2id.json"
ID2LABEL_PATH: "data/id2label.json"
MODEL_SAVE_PATH: "checkpoints/best_model.pt"

# Others
SEED: 42